name: CI Build
on:
  pull_request:
    branches: 
      - main

jobs:
  Linting:
    runs-on: mcr.microsoft.com/powershell:lts-7.2-alpine-3.14

    strategy:
      matrix:
        filetypes:
          - azuredeploy.json

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checking ${{ matrix.filetypes }}
        run: | 
          .github/script/verify.sh ${{ matrix.filetypes }}